# Generated by Django 4.0.8 on 2023-09-14 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warehouse_owner', 'Warehouse Owner'), ('delivery_person', 'Delivery Person'), ('manager', 'Manager'), ('product_maker', 'Product Maker'), ('qa', 'QA'), ('other', 'Other')], max_length=255)),
                ('salary', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
