# Generated by Django 4.0.8 on 2024-01-06 11:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('manager', 'Manager'), ('warehouse_owner', 'Warehouse Owner'), ('delivery_person', 'Delivery Person'), ('product_maker', 'Product Maker'), ('qa', 'QA'), ('other', 'Other')], max_length=255),
        ),
    ]
