# Generated by Django 4.0.8 on 2023-09-25 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_stocks_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPrepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perchase_qty', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('prepared', 'Prepared')], max_length=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.orders')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.stocks')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.warehouse')),
            ],
        ),
    ]
