# Generated by Django 4.0.8 on 2023-09-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee'),
        ('products', '0008_delivery_delivery_person_and_more'),
        ('staffs', '0002_rename_perchase_qty_orderprepare_purchase_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_type', models.CharField(choices=[('order', 'Order'), ('employee_salary', 'Employee salary'), ('product_making_expense', 'Product Making Expense'), ('raw_material_expense', 'Raw Material Expense'), ('other_expense', 'Other Expense')], max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.orders')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.CharField(choices=[('credit', 'CREDIT'), ('debit', 'DEBIT')], max_length=50)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.employee')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_line', to='staffs.ledger')),
                ('orderline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.orderlines')),
            ],
        ),
    ]
