# Generated by Django 4.0.8 on 2023-10-03 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_ledger_ledgerline'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprepare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
