# Generated by Django 4.0.8 on 2024-01-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_product_maker'),
        ('staffs', '0004_orderprepare_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprepare',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderprepare',
            name='product_attribute',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productchangepriceattributes'),
            preserve_default=False,
        ),
    ]
