# Generated by Django 4.0.8 on 2023-10-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
