# Generated by Django 4.0.8 on 2023-10-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_vouchers_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications_app', '0002_notification_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_person', to='products.orders'),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='for_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='prepare_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prepare_order', to='products.orders'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='products.orders'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.delivery'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
