# Generated by Django 4.0.8 on 2023-10-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_notification_contact_person_notification_for_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='contact_person',
        ),
    ]
