# Generated by Django 4.0.8 on 2023-08-19 03:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=200)),
                ('on_above_purchase', models.FloatField(blank=True, null=True)),
                ('off_price', models.FloatField(blank=True, null=True)),
                ('percent_off', models.FloatField(blank=True, null=True)),
                ('promocode_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expirable', models.BooleanField(blank=True, default=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='Warehouse',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='user_who_have_used',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='users',
        ),
        migrations.RenameField(
            model_name='orderlines',
            old_name='per_order_amount',
            new_name='sub_total_amount',
        ),
        migrations.RenameField(
            model_name='orderlines',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='shop_id',
            new_name='warehouse_id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='name_of_shop',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='created_seller',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='deals_of_day',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ingredience',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_day',
        ),
        migrations.AddField(
            model_name='orders',
            name='total_discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.state'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Deals_of_day',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AddField(
            model_name='vouchers',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.products'),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='user_who_have_used',
            field=models.ManyToManyField(related_name='user_who_have_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_user_to_promo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='with_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='with_product', to='products.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='vouchers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vouchers'),
        ),
    ]
