# Generated by Django 4.0.8 on 2023-08-22 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_vouchers_rename_store_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='stop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='expirable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='user_who_have_used',
            field=models.ManyToManyField(blank=True, related_name='user_who_have_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucher_type',
            field=models.CharField(choices=[('on_above_purchase', 'On Above Purchase'), ('deals_of_day', 'Deals of Day'), ('product_together', 'Product Together'), ('promocode', 'Promocode')], max_length=200),
        ),
    ]
