# Generated by Django 4.0.8 on 2023-08-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_vouchers_stop_alter_vouchers_expirable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vouchers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.vouchers'),
        ),
    ]
