# Generated by Django 3.2.5 on 2022-10-08 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221008_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals_of_day',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 6, 53, 40, 554291)),
            preserve_default=False,
        ),
    ]
