# Generated by Django 4.0.8 on 2023-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_vouchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
