# Generated by Django 3.2.5 on 2022-10-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_deals_of_day_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='expirable',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='user_who_have_used',
        ),
    ]
