# Generated by Django 3.2.5 on 2022-10-08 09:50

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20221008_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 8, 9, 49, 55, 365170, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='expirable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 9, 50, 21, 620251)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='user_who_have_used',
            field=models.ManyToManyField(related_name='user_who_have_used', to=settings.AUTH_USER_MODEL),
        ),
    ]
