# Generated by Django 4.0.8 on 2023-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_warehouse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='selected_product_varient',
            field=models.CharField(default='A1,High,', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('order_prepared', 'Order Prepared'), ('order_confirm', 'Order Confirm'), ('order_cancel', 'Order Cancel'), ('order_delivering', 'Order Delivering'), ('order_shipped', 'Order Shipped')], default='order_confirm', max_length=100),
        ),
    ]
