# Generated by Django 3.2.5 on 2022-10-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221008_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='stock_day',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 10, 8, 11, 17, 56, 137029)),
            preserve_default=False,
        ),
    ]
