# Generated by Django 4.0.8 on 2023-09-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderlines_selected_product_varient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='product_attributes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productchangepriceattributes'),
            preserve_default=False,
        ),
    ]
