# Generated by Django 4.0.8 on 2023-09-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee'),
        ('products', '0007_stocks_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_person',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=100),
        ),
    ]
