# Generated by Django 3.2.5 on 2022-10-12 02:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stocks_stock_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_product_varient',
            field=models.CharField(default=datetime.datetime(2022, 10, 12, 2, 24, 2, 227950), max_length=100),
            preserve_default=False,
        ),
    ]
