# Generated by Django 3.2.5 on 2022-10-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_selected_product_varient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.discount'),
        ),
    ]
