# Generated by Django 4.0.8 on 2023-10-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delivery_delivery_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Delivering', 'Delivering'), ('Shipped', 'Shipped')], default='Confirm', max_length=100),
        ),
    ]
