# Generated by Django 3.2.5 on 2022-10-13 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_orders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlines',
            name='per_order_amount',
            field=models.FloatField(default=1.1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
