# Generated by Django 4.0.8 on 2023-10-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], max_length=100),
        ),
    ]
