# Generated by Django 4.0.8 on 2023-10-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delivery_updated_at_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
