# Generated by Django 3.2.5 on 2022-10-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_orderlines_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deals_of_day',
            field=models.ManyToManyField(blank=True, null=True, to='products.Deals_of_day'),
        ),
    ]
