# Generated by Django 4.0.8 on 2024-01-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_vouchers_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='varified',
            new_name='verified',
        ),
    ]
