# Generated by Django 4.0.8 on 2024-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_varified_otpmodel_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
