# Generated by Django 4.0.8 on 2024-01-09 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_warehouse_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_maker',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
