# Generated by Django 4.0.8 on 2024-02-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_delivery_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Started', 'Started'), ('Delivering', 'Delivering'), ('Shipped', 'Shipped')], default='Confirm', max_length=100),
        ),
    ]
