# Generated by Django 4.0.8 on 2024-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_warehouse_is_approved_alter_delivery_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_product_finest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_qa_verified',
            field=models.BooleanField(default=False),
        ),
    ]
