# Generated by Django 4.0.8 on 2024-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_transaction_provider_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Cancel', 'Cancel')], max_length=100),
        ),
    ]
