# Generated by Django 4.0.8 on 2024-02-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='otp_code',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
