# Generated by Django 4.0.8 on 2024-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delivery_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
